/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_tags.h"
#include "bar_status.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_statuscolors.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "aspectresize.h"
#include "cfacts.h"
#include "cmdcustomize.h"
#include "cyclelayouts.h"
#include "fakefullscreenclient.h"
#include "focusdir.h"
#include "fullscreen.h"
#include "keymodes.h"
#include "mpdcontrol.h"
#include "placemouse.h"
#include "roundedcorners.h"
#include "scratchpad.h"
#include "selfrestart.h"
#include "setborderpx.h"
#include "vanitygaps.h"
#include "warp.h"
#include "winview.h"
#include "xkb.h"
#include "xrdb.h"
/* Layouts */
#include "layout_monocle.h"
#include "layout_tile.h"

