/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_tags.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_statuscolors.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "aspectresize.c"
#include "cfacts.c"
#include "cmdcustomize.c"
#include "cyclelayouts.c"
#include "fakefullscreenclient.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "keymodes.c"
#include "mpdcontrol.c"
#include "placemouse.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "setborderpx.c"
#include "vanitygaps.c"
#include "warp.c"
#include "winview.c"
#include "xkb.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"

